import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import os

# --- Configuration ---
DATA_FILE = 'data/banxico_rates.csv'
os.makedirs('plots', exist_ok=True)
PLOT_DIR = 'plots'
PLOT_FILE = f'{PLOT_DIR}/data_availability.png'

# Ensure plots directory exists
os.makedirs(PLOT_DIR, exist_ok=True)

print("Generating visualization...")

try:
    # 1. Read the data generated by the pipeline
    df = pd.read_csv(DATA_FILE, index_col='Date', parse_dates=True)

    # 2. Create a boolean mask: True if data exists, False if NaN (no auction)
    # We resample by Quarter ('Q') to make the chart readable over 40+ years.
    # .any() means: Did at least one auction happen in this quarter?
    presence_df = df.notna().resample('Q').any().T # Transpose to put instruments on Y-axis

    # --- Plotting ---
    plt.figure(figsize=(15, 10))

    # Create heatmap
    # cmap defines colors: False=light red, True=green
    ax = sns.heatmap(presence_df, cmap=["#ffebeb", "#28a745"], cbar=False, 
                     linewidths=0.5, linecolor='white', square=False)

    # Formatting the chart
    plt.title('Timeline of Mexican Government Securities Availability (Data Presence)', fontsize=16, pad=20)
    plt.ylabel('Instrument', fontsize=12)
    plt.xlabel('Year', fontsize=12)

    # Format X-axis to show years clearly
    # Get current labels (dates) and just extract the year for cleaner view
    labels = [item.get_text()[:4] for item in ax.get_xticklabels()]
    ax.set_xticklabels(labels, rotation=45, ha='right')
    
    # Only show every 4th tick on x-axis to avoid clutter
    for i, label in enumerate(ax.xaxis.get_ticklabels()):
        if i % 4 != 0:
            label.set_visible(False)

    plt.tight_layout()

    # 3. Save the image
    plt.savefig(PLOT_FILE, dpi=150, bbox_inches='tight')
    print(f"Success: Plot saved to {PLOT_FILE}")

except FileNotFoundError:
    print(f"Error: {DATA_FILE} not found. Run the data pipeline first.")
except Exception as e:
    print(f"An error occurred during plotting: {e}")
